# Generated by Django 5.2.17 on 2026-08-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_seed_catalog_options'),
        ('files', '0001_initial'),
        ('terms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAuditSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_channel', models.CharField(choices=[('file', 'Arquivo'), ('external_link', 'Link externo')], max_length=20)),
                ('external_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('external_link_declaration', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('submitted', 'Enviada'), ('needs_correction', 'Correção necessária'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_submissions', to='applications.serviceapplication')),
                ('file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audit_submissions', to='files.fileasset')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset_audit_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetAuditReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('needs_correction', 'Correção solicitada')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='audits.datasetauditsubmission')),
            ],
            options={
                'db_table': 'dataset_audit_reviews',
            },
        ),
        migrations.CreateModel(
            name='DatasetAuditResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('convert_to_consultation', 'Converter em consulta'), ('reject_application', 'Rejeitar inscrição'), ('transfer_term', 'Transferir de período')], max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_resolutions', to='applications.serviceapplication')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_resolutions', to=settings.AUTH_USER_MODEL)),
                ('target_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audit_resolutions', to='terms.academicterm')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='audits.datasetauditsubmission')),
            ],
            options={
                'db_table': 'dataset_audit_resolutions',
            },
        ),
        migrations.AddConstraint(
            model_name='datasetauditsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('submission_channel__in', ['file', 'external_link'])), name='chk_audit_submissions_channel'),
        ),
        migrations.AddConstraint(
            model_name='datasetauditsubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_url__isnull', True), ('file_asset__isnull', False), ('submission_channel', 'file')), models.Q(('external_link_declaration', True), ('external_url__isnull', False), ('file_asset__isnull', True), ('submission_channel', 'external_link')), _connector='OR'), name='chk_audit_submissions_single_channel'),
        ),
        migrations.AddConstraint(
            model_name='datasetauditreview',
            constraint=models.UniqueConstraint(fields=('submission',), name='uq_dataset_audit_reviews_submission'),
        ),
        migrations.AddConstraint(
            model_name='datasetauditreview',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['approved', 'rejected', 'needs_correction'])), name='chk_audit_reviews_outcome'),
        ),
        migrations.AddConstraint(
            model_name='datasetauditresolution',
            constraint=models.UniqueConstraint(fields=('submission',), name='uq_dataset_audit_resolutions_submission'),
        ),
        migrations.AddConstraint(
            model_name='datasetauditresolution',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__in', ['convert_to_consultation', 'reject_application', 'transfer_term'])), name='chk_audit_resolutions_resolution'),
        ),
        migrations.AddConstraint(
            model_name='datasetauditresolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution', 'transfer_term'), ('target_term__isnull', False)), models.Q(('resolution', 'convert_to_consultation'), ('target_term__isnull', True)), models.Q(('resolution', 'reject_application'), ('target_term__isnull', True)), _connector='OR'), name='chk_audit_resolutions_transfer_requires_term'),
        ),
    ]
