# Generated by Django 5.2.17 on 2026-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('period', models.CharField(choices=[('first', 'Primeiro Semestre'), ('second', 'Segundo Semestre')], max_length=10)),
                ('teaching_start_date', models.DateField(blank=True, null=True)),
                ('teaching_end_date', models.DateField(blank=True, null=True)),
                ('submission_start_date', models.DateField(blank=True, null=True)),
                ('submission_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academic_terms',
                'ordering': ['-year', 'period'],
                'constraints': [models.UniqueConstraint(fields=('year', 'period'), name='uq_academic_terms_year_period'), models.CheckConstraint(condition=models.Q(('period__in', ['first', 'second'])), name='chk_academic_terms_period')],
            },
        ),
    ]
