# Generated by Django 5.2.17 on 2026-08-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSlipPaymentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_slip_reference', models.CharField(max_length=60, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('bank_status', models.CharField(choices=[('E', 'Emitido'), ('P', 'Pago'), ('V', 'Verificar'), ('C', 'Cancelado')], default='E', max_length=1)),
                ('document_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_slip_instrument', to='payments.paymentinstrument')),
                ('pdf_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_slips', to='files.fileasset')),
            ],
            options={
                'db_table': 'bank_slip_payment_instruments',
                'ordering': ['-created_at'],
            },
        ),
    ]
