# Generated by Django 5.2.17 on 2026-08-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_reference', models.CharField(max_length=35)),
                ('raw_payload', models.JSONField()),
                ('token_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pix_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PixPaymentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_reference', models.CharField(max_length=35, unique=True)),
                ('qr_code_payload', models.CharField(max_length=255)),
                ('external_status', models.CharField(blank=True, max_length=20, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_tax_id', models.CharField(blank=True, max_length=14, null=True)),
                ('bank_return_code', models.CharField(blank=True, max_length=35, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_instrument', to='payments.paymentinstrument')),
                ('qr_code_image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pix_instruments', to='files.fileasset')),
            ],
            options={
                'db_table': 'pix_payment_instruments',
                'ordering': ['-created_at'],
            },
        ),
    ]
