"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

# Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file if present (optional: in Portainer values come from the Stack env vars)
env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

# Add apps/ directory to sys.path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'django_extensions',

    # Internal apps (from apps/ directory)
    'users.apps.UsersConfig',
    'base.apps.BaseConfig',
    'terms.apps.TermsConfig',
    'files.apps.FilesConfig',
    'applications.apps.ApplicationsConfig',
    'audits.apps.AuditsConfig',
    'payments.apps.PaymentsConfig',
    'pix.apps.PixConfig',
    'bank_slips.apps.BankSlipsConfig',
    'meetings.apps.MeetingsConfig',
    'notifications.apps.NotificationsConfig',
    'documents.apps.DocumentsConfig',

    # USP Socialite
    'senhaunica_socialite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.enable_local_login',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default='sqlite:///db.sqlite3'),
}

AUTH_USER_MODEL = 'users.User'

# Flag que controla o login local (usuário/senha). Se False, o backend de
# autenticação local é removido e apenas a Senha Única USP é aceita.
ENABLE_LOCAL_LOGIN = env('ENABLE_LOCAL_LOGIN', default=True)

AUTHENTICATION_BACKENDS = [
    'senhaunica_socialite.backends.SenhaUnicaBackend',
]

if ENABLE_LOCAL_LOGIN:
    AUTHENTICATION_BACKENDS.append('django.contrib.auth.backends.ModelBackend')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Redirects for Auth
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/auth/login/'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (private storage)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Use WhiteNoise storage only in production (DEBUG=False)
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Celery
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html
CELERY_BROKER_URL = env('REDIS_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE


# ---- E-mail (notificações) ----
# E-mail padrão usado no remetente dos disparos de notificação.
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@cea.ime.usp.br')
# Destinatário dos avisos internos para a equipe CEA.
NOTIFICATION_CENTER_EMAIL = env('NOTIFICATION_CENTER_EMAIL', default='cea@ime.usp.br')


# ---- Integração Pix (API REST/JSON) ----
PIX_WEBHOOK_TOKEN = env('PIX_WEBHOOK_TOKEN', default='dev-webhook-token')
PIX_BASE_URL = env('PIX_BASE_URL', default='https://example.com/pix')
PIX_USERNAME = env('PIX_USERNAME', default='')
PIX_PASSWORD = env('PIX_PASSWORD', default='')
PIX_EXPIRATION_SECONDS = env.int('PIX_EXPIRATION_SECONDS', default=3600)
PIX_CODIGO_FONTE_RECURSO = env.int('PIX_CODIGO_FONTE_RECURSO', default=423)
PIX_CODIGO_UNIDADE_DESPESA = env.int('PIX_CODIGO_UNIDADE_DESPESA', default=1)
PIX_ESTRUTURA_HIERARQUICA = env('PIX_ESTRUTURA_HIERARQUICA', default='\\DISTRIBUIDOR')
# Máximo de dias aceito para o período de reconciliação (listarConcluidos).
PIX_RECONCILIATION_MAX_DAYS = env.int('PIX_RECONCILIATION_MAX_DAYS', default=30)


# ---- Integração Boleto (SOAP/WSDL) ----
BANK_SLIP_WSDL_URL = env(
    'BANK_SLIP_WSDL_URL',
    default='https://dev.uspdigital.usp.br/wsboleto/wsdl/boleto.wsdl',
)
BANK_SLIP_USERNAME = env('BANK_SLIP_USERNAME', default='')
BANK_SLIP_PASSWORD = env('BANK_SLIP_PASSWORD', default='')
BANK_SLIP_DUE_DAYS = env.int('BANK_SLIP_DUE_DAYS', default=3)
BANK_SLIP_CODIGO_FONTE_RECURSO = env.int('BANK_SLIP_CODIGO_FONTE_RECURSO', default=423)
BANK_SLIP_CODIGO_UNIDADE_DESPESA = env.int('BANK_SLIP_CODIGO_UNIDADE_DESPESA', default=1)
BANK_SLIP_ESTRUTURA_HIERARQUICA = env('BANK_SLIP_ESTRUTURA_HIERARQUICA', default='\\DISTRIBUIDOR')
