# Generated by Django 5.2.17 on 2026-08-11 19:15

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_applicationevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('application_fee', 'Taxa de inscrição'), ('project_fee', 'Taxa de projeto'), ('supplement_fee', 'Taxa complementar')], max_length=30)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('is_waived', models.BooleanField(default=False)),
                ('waiver_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fee_requirements', to='applications.serviceapplication')),
            ],
            options={
                'db_table': 'fee_requirements',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pix', 'Pix'), ('bank_slip', 'Boleto'), ('manual', 'Manual')], max_length=20)),
                ('state', models.CharField(choices=[('created', 'Criado'), ('active', 'Ativo'), ('paid', 'Pago'), ('expired', 'Expirado'), ('canceled', 'Cancelado'), ('superseded', 'Substituído'), ('failed', 'Falhou'), ('manual_confirmed', 'Confirmado manualmente'), ('requires_review', 'Exige revisão')], default='created', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('active_unique_fee_token', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_instruments', to=settings.AUTH_USER_MODEL)),
                ('fee_requirement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_instruments', to='payments.feerequirement')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_instruments', to='payments.paymentinstrument')),
            ],
            options={
                'db_table': 'payment_instruments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualPaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payment_confirmations', to=settings.AUTH_USER_MODEL)),
                ('payment_instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_confirmation', to='payments.paymentinstrument')),
            ],
            options={
                'db_table': 'manual_payment_confirmations',
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('approved', 'Aprovado'), ('executed', 'Executado'), ('denied', 'Negado')], default='requested', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refund_requests', to='applications.serviceapplication')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_executed', to=settings.AUTH_USER_MODEL)),
                ('payment_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='refund_requests', to='payments.paymentinstrument')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='feerequirement',
            constraint=models.CheckConstraint(condition=models.Q(('fee_type__in', ['application_fee', 'project_fee', 'supplement_fee'])), name='chk_fee_requirements_fee_type'),
        ),
        migrations.AddConstraint(
            model_name='feerequirement',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(models.F('base_amount'), '+', models.F('adjustment_amount')))), name='chk_fee_requirements_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstrument',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['pix', 'bank_slip', 'manual'])), name='chk_payment_instruments_method'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstrument',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['created', 'active', 'paid', 'expired', 'canceled', 'superseded', 'failed', 'manual_confirmed', 'requires_review'])), name='chk_payment_instruments_state'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstrument',
            constraint=models.UniqueConstraint(fields=('active_unique_fee_token',), name='uq_payment_instruments_active_token'),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['requested', 'approved', 'executed', 'denied'])), name='chk_refund_requests_status'),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='chk_refund_requests_amount'),
        ),
    ]
