# Generated by Django 5.2.17 on 2026-08-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_codpes_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('teacher', 'Docente'), ('secretariat', 'Secretaria'), ('administrator', 'Administrador')], default='candidate', max_length=20),
        ),
    ]
