# Generated by Django 5.2.17 on 2026-08-11 18:42

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_attachments',
            },
        ),
        migrations.CreateModel(
            name='ApplicationCatalogSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_catalog_selections',
            },
        ),
        migrations.CreateModel(
            name='CatalogOption',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('institutional_tie', 'Vínculo institucional'), ('project_purpose', 'Finalidade do projeto'), ('knowledge_area', 'Área de conhecimento'), ('funding_agency', 'Agência de fomento')], max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_options',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=9)),
                ('modality', models.CharField(choices=[('project', 'Projeto'), ('consultation', 'Consulta')], max_length=20)),
                ('lifecycle_status', models.CharField(choices=[('submitted', 'Submetida'), ('awaiting_dataset_submission', 'Aguardando envio de dados'), ('awaiting_dataset_review', 'Aguardando análise de dados'), ('awaiting_dataset_correction', 'Aguardando correção de dados'), ('dataset_rejected_pending_resolution', 'Dados rejeitados — aguardando decisão'), ('awaiting_payment', 'Aguardando pagamento'), ('awaiting_screening_scheduling', 'Aguardando agendamento da triagem'), ('awaiting_screening_result', 'Aguardando resultado da triagem'), ('awaiting_consultation_scheduling', 'Aguardando agendamento da reunião de consulta'), ('awaiting_consultation_result', 'Aguardando resultado da reunião de consulta'), ('approved_as_project', 'Aprovado como projeto'), ('approved_as_consultation', 'Aprovado como consulta'), ('not_approved', 'Não aprovado'), ('transferred', 'Transferida'), ('canceled', 'Cancelada')], default='submitted', max_length=60)),
                ('payment_state', models.CharField(blank=True, choices=[('pending', 'Pendente'), ('partially_paid', 'Parcialmente pago'), ('paid', 'Pago'), ('refunded', 'Reembolsado')], max_length=30, null=True)),
                ('dataset_audit_required', models.BooleanField(default=False)),
                ('dataset_audit_state', models.CharField(blank=True, choices=[('not_required', 'Não exigida'), ('awaiting_submission', 'Aguardando envio'), ('awaiting_review', 'Aguardando análise'), ('needs_correction', 'Correção necessária'), ('rejected_pending_resolution', 'Rejeitada — aguardando decisão'), ('approved', 'Aprovada')], max_length=40, null=True)),
                ('origin', models.CharField(choices=[('created_portal', 'Criada no portal'), ('imported', 'Importada')], default='created_portal', max_length=20)),
                ('modality_credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transfer_pending', models.BooleanField(default=False)),
                ('transfer_reason', models.TextField(blank=True, null=True)),
                ('researcher_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('has_whatsapp', models.BooleanField(default=False)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mentor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wants_refund_receipt', models.BooleanField(default=False)),
                ('refund_receipt_details', models.TextField(blank=True, null=True)),
                ('refund_account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_account_holder_tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('refund_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_branch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_bank_account_type', models.CharField(blank=True, choices=[('checking', 'Conta corrente'), ('savings', 'Conta poupança')], max_length=20, null=True)),
                ('project_title', models.TextField(blank=True, null=True)),
                ('context_summary', models.TextField(blank=True, null=True)),
                ('general_objectives', models.TextField(blank=True, null=True)),
                ('variables_and_measurements', models.TextField(blank=True, null=True)),
                ('contextual_factors', models.TextField(blank=True, null=True)),
                ('sampling_and_limitations', models.TextField(blank=True, null=True)),
                ('data_management_plan', models.TextField(blank=True, null=True)),
                ('expected_results', models.TextField(blank=True, null=True)),
                ('expected_support', models.TextField(blank=True, null=True)),
                ('data_already_collected', models.BooleanField(blank=True, null=True)),
                ('data_use_authorization_accepted', models.BooleanField(blank=True, null=True)),
                ('mentor_declaration_accepted', models.BooleanField(blank=True, null=True)),
                ('legacy_contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_contact_tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_applications',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
