# Generated by Django 5.2.17 on 2026-08-11 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('files', '0001_initial'),
        ('terms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationattachment',
            name='file_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_attachment', to='files.fileasset'),
        ),
        migrations.AddConstraint(
            model_name='catalogoption',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='uq_catalog_options_category_code'),
        ),
        migrations.AddConstraint(
            model_name='catalogoption',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['institutional_tie', 'project_purpose', 'knowledge_area', 'funding_agency'])), name='chk_catalog_options_category'),
        ),
        migrations.AddField(
            model_name='applicationcatalogselection',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='application_selections', to='applications.catalogoption'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='terms.academicterm'),
        ),
        migrations.AddField(
            model_name='applicationcatalogselection',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_selections', to='applications.serviceapplication'),
        ),
        migrations.AddField(
            model_name='applicationattachment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='applications.serviceapplication'),
        ),
        migrations.AddIndex(
            model_name='serviceapplication',
            index=models.Index(fields=['term'], name='idx_svc_applications_term'),
        ),
        migrations.AddIndex(
            model_name='serviceapplication',
            index=models.Index(fields=['owner'], name='idx_svc_applications_owner'),
        ),
        migrations.AddIndex(
            model_name='serviceapplication',
            index=models.Index(fields=['protocol'], name='idx_svc_applications_protocol'),
        ),
        migrations.AddConstraint(
            model_name='serviceapplication',
            constraint=models.UniqueConstraint(fields=('protocol',), name='uq_service_applications_protocol'),
        ),
        migrations.AddConstraint(
            model_name='serviceapplication',
            constraint=models.CheckConstraint(condition=models.Q(('modality__in', ['project', 'consultation'])), name='chk_service_applications_modality'),
        ),
        migrations.AddConstraint(
            model_name='serviceapplication',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['created_portal', 'imported'])), name='chk_service_applications_origin'),
        ),
        migrations.AddConstraint(
            model_name='serviceapplication',
            constraint=models.CheckConstraint(condition=models.Q(('modality_credit_amount__gte', 0)), name='chk_service_applications_modality_credit'),
        ),
        migrations.AddConstraint(
            model_name='applicationcatalogselection',
            constraint=models.UniqueConstraint(fields=('application', 'option'), name='uq_application_catalog_selections'),
        ),
        migrations.AddConstraint(
            model_name='applicationattachment',
            constraint=models.UniqueConstraint(fields=('file_asset',), name='uq_application_attachments_file'),
        ),
    ]
