# Generated by Django 5.2.17 on 2026-08-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_applicationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('meeting_mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'Presencial')], max_length=20)),
                ('virtual_link', models.CharField(blank=True, max_length=2048, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('decision', models.CharField(blank=True, choices=[('approved_as_consultation', 'Aprovado como consulta'), ('not_approved', 'Não aprovado')], max_length=40, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('teacher_feedback', models.CharField(blank=True, choices=[('consultation_completed', 'Reunião realizada'), ('consultation_not_completed', 'Reunião não realizada')], max_length=50, null=True)),
                ('state', models.CharField(choices=[('scheduled', 'Agendada'), ('rescheduled', 'Reagendada'), ('canceled', 'Cancelada'), ('completed', 'Concluída')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='consultation_meeting', to='applications.serviceapplication')),
            ],
            options={
                'db_table': 'consultation_meetings',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('meeting_mode__in', ['online', 'in_person'])), name='chk_consultation_meetings_meeting_mode'), models.CheckConstraint(condition=models.Q(('decision__in', ['approved_as_consultation', 'not_approved'])), name='chk_consultation_meetings_decision'), models.CheckConstraint(condition=models.Q(('teacher_feedback__in', ['consultation_completed', 'consultation_not_completed'])), name='chk_consultation_meetings_feedback'), models.CheckConstraint(condition=models.Q(('state__in', ['scheduled', 'rescheduled', 'canceled', 'completed'])), name='chk_consultation_meetings_state'), models.CheckConstraint(condition=models.Q(models.Q(('meeting_mode', 'online'), ('virtual_link__isnull', False)), models.Q(('meeting_mode', 'in_person'), ('place__isnull', False)), _connector='OR'), name='chk_consultation_meetings_mode_location')],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('meeting_mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'Presencial')], max_length=20)),
                ('virtual_link', models.CharField(blank=True, max_length=2048, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('decision', models.CharField(blank=True, choices=[('approved_as_project', 'Aprovado como projeto'), ('approved_as_consultation', 'Aprovado como consulta'), ('not_approved', 'Não aprovado')], max_length=40, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('teacher_feedback', models.CharField(blank=True, choices=[('screening_completed', 'Triagem realizada'), ('screening_not_completed', 'Triagem não realizada')], max_length=50, null=True)),
                ('state', models.CharField(choices=[('scheduled', 'Agendada'), ('rescheduled', 'Reagendada'), ('canceled', 'Cancelada'), ('completed', 'Concluída')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='project_screening', to='applications.serviceapplication')),
            ],
            options={
                'db_table': 'project_screenings',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('meeting_mode__in', ['online', 'in_person'])), name='chk_project_screenings_meeting_mode'), models.CheckConstraint(condition=models.Q(('decision__in', ['approved_as_project', 'approved_as_consultation', 'not_approved'])), name='chk_project_screenings_decision'), models.CheckConstraint(condition=models.Q(('teacher_feedback__in', ['screening_completed', 'screening_not_completed'])), name='chk_project_screenings_feedback'), models.CheckConstraint(condition=models.Q(('state__in', ['scheduled', 'rescheduled', 'canceled', 'completed'])), name='chk_project_screenings_state'), models.CheckConstraint(condition=models.Q(models.Q(('meeting_mode', 'online'), ('virtual_link__isnull', False)), models.Q(('meeting_mode', 'in_person'), ('place__isnull', False)), _connector='OR'), name='chk_project_screenings_mode_location')],
            },
        ),
    ]
