# Generated by Django 5.2.17 on 2026-08-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationevent'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consultationmeeting',
            name='chk_consultation_meetings_decision',
        ),
        migrations.AlterField(
            model_name='consultationmeeting',
            name='decision',
            field=models.CharField(blank=True, choices=[('approved_as_project', 'Aprovado como projeto'), ('approved_as_consultation', 'Aprovado como consulta'), ('not_approved', 'Não aprovado')], max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='consultationmeeting',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['approved_as_project', 'approved_as_consultation', 'not_approved'])), name='chk_consultation_meetings_decision'),
        ),
    ]
