# Generated by Django 5.2.17 on 2026-08-11 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_applicationevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyOwnershipClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, max_length=9, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('code_sent', 'Código enviado'), ('verified', 'Verificada'), ('rejected', 'Rejeitada'), ('manually_approved', 'Aprovada manualmente')], default='pending', max_length=30)),
                ('verification_token_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_claims', to='applications.serviceapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_claims_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_ownership_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legacy_ownership_claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application'], name='idx_legacy_claims_application'), models.Index(fields=['status'], name='idx_legacy_claims_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'code_sent', 'verified', 'rejected', 'manually_approved'])), name='chk_legacy_ownership_claims_status')],
            },
        ),
    ]
