# Generated by Django 5.2.17 on 2026-08-11 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('purpose', models.CharField(choices=[('application_attachment', 'Anexo da inscrição'), ('dataset_submission', 'Arquivo de auditoria'), ('payment_receipt', 'Comprovante'), ('pix_qrcode_image', 'Imagem QR'), ('pix_pdf', 'PDF do Pix'), ('bank_slip_pdf', 'PDF do boleto'), ('document_export', 'Documento gerado')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_assets', to='applications.serviceapplication')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_file_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_assets',
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0), ('size_bytes__isnull', True), _connector='OR'), name='chk_file_assets_size')],
            },
        ),
    ]
