# Generated by Django 5.2.17 on 2026-08-11 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_applicationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('audience', models.CharField(choices=[('candidate', 'Candidato'), ('center', 'Equipe CEA'), ('teacher', 'Docente'), ('secretariat', 'Secretaria')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('audience__in', ['candidate', 'center', 'teacher', 'secretariat'])), name='chk_notification_templates_audience')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_dispatches', to='applications.serviceapplication')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispatches', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_dispatches',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'sent', 'failed'])), name='chk_notification_dispatches_status')],
            },
        ),
    ]
